"""
Django settings for restaurant_booking project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--%m5*^=v+k0m+5892wzichk$_rhekn#-t+_e=2#4(y*qa0orvx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Modern admin theme
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework
    'corsheaders',     # CORS pour React
    'reservations',    # Votre app
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS en premier
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restaurant_booking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ADD THIS LINE
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurant_booking.wsgi.application'


# Database - PostgreSQL Configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'restaurant_booking',
        'USER': 'postgres',
        'PASSWORD': 'simanjali',  # Le mot de passe que vous avez défini
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Alternative: Base de données SQLite pour commencer (plus simple)
# Décommentez ceci et commentez PostgreSQL si vous voulez commencer avec SQLite
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'  # Français
TIME_ZONE = 'Africa/Casablanca'  

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

# CORS Configuration pour React
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True


# Static files configuration (make sure this exists)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Replace your JAZZMIN_SETTINGS in settings.py with this:

JAZZMIN_SETTINGS = {
    "site_title": "Resto Pêcheur Admin",
    "site_header": "Resto Pêcheur",
    "site_brand": "Resto Pêcheur",
    "site_logo": "admin/img/logo.png",
    "login_logo": "admin/img/logo.png",
    "site_logo_classes": "",
    "welcome_sign": "De l'océan à votre assiette - Administration",
    "copyright": "Resto Pêcheur 2025 - من المحيط إلى طبقكم",
    
    # Ocean theme
    "theme": "cerulean",
    "dark_mode_theme": None,
    
    # Custom ocean styling
    "custom_css": "admin/css/theme.css", 
    "custom_js": None,
    
    # REMOVED ALL TOP NAVIGATION LINKS
    "topmenu_links": [],
    
    # REMOVED ALL USER MENU LINKS
    "usermenu_links": [],
    
    # Menu ordering
    "order_with_respect_to": ["reservations", "auth"],
    
    # Ocean-themed icons
    "icons": {
        "auth": "fas fa-anchor",
        "auth.user": "fas fa-user-tie", 
        "reservations.Reservation": "fas fa-fish",
        "reservations.TimeSlot": "fas fa-clock",
        "reservations.SpecialDate": "fas fa-calendar-alt",
        "reservations.Restaurant": "fas fa-store",
    },
    
    "default_icon_parents": "fas fa-waves",
    "default_icon_children": "fas fa-circle",
    
    "related_modal_active": False,
    
    # Hide unnecessary models for single restaurant
    "hide_apps": [],
    "hide_models": [
        "auth.Group",               # Single admin, no groups needed
        "reservations.Restaurant",  # HIDE RESTAURANT MODEL - ONLY ONE RESTAURANT
    ],
    
    "show_sidebar": True,
    "navigation_expanded": True,
    "changeform_format": "horizontal_tabs",
}