# Generated by Django 5.2.1 on 2025-06-01 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Heure')),
                ('number_of_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de personnes')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='pending', max_length=20, verbose_name='Statut')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Demandes spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anoual Restaurant', max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=50)),
                ('opening_time', models.TimeField(default='11:00')),
                ('closing_time', models.TimeField(default='22:00')),
                ('closed_on_monday', models.BooleanField(default=False)),
                ('closed_on_tuesday', models.BooleanField(default=False)),
                ('closed_on_wednesday', models.BooleanField(default=False)),
                ('closed_on_thursday', models.BooleanField(default=False)),
                ('closed_on_friday', models.BooleanField(default=False)),
                ('closed_on_saturday', models.BooleanField(default=False)),
                ('closed_on_sunday', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fermé')),
                ('special_opening_time', models.TimeField(blank=True, null=True, verbose_name='Ouverture spéciale')),
                ('special_closing_time', models.TimeField(blank=True, null=True, verbose_name='Fermeture spéciale')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Raison')),
            ],
            options={
                'verbose_name': 'Date spéciale',
                'verbose_name_plural': 'Dates spéciales',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Heure')),
                ('max_reservations', models.IntegerField(default=10, verbose_name='Nombre max de réservations')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['time'],
            },
        ),
    ]
