# Generated by Django 5.2.1 on 2025-06-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Annulé le'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de table'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='number_of_tables',
            field=models.IntegerField(default=20, verbose_name='Nombre de tables'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'status'], name='reservation_date_b616a1_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'time'], name='reservation_date_295b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='reservation_status_f1a03a_idx'),
        ),
        migrations.AddIndex(
            model_name='specialdate',
            index=models.Index(fields=['date'], name='reservation_date_2cb9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='specialdate',
            index=models.Index(fields=['date', 'is_closed'], name='reservation_date_616148_idx'),
        ),
    ]
