# Generated by Django 5.2.1 on 2025-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_cancelled_at_reservation_confirmed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Resto Pêcheur', editable=False, max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=50)),
                ('number_of_tables', models.IntegerField(default=20, verbose_name='Nombre de tables')),
                ('opening_time', models.TimeField(default='11:00')),
                ('closing_time', models.TimeField(default='22:00')),
                ('closed_on_monday', models.BooleanField(default=False)),
                ('closed_on_tuesday', models.BooleanField(default=False)),
                ('closed_on_wednesday', models.BooleanField(default=False)),
                ('closed_on_thursday', models.BooleanField(default=False)),
                ('closed_on_friday', models.BooleanField(default=False)),
                ('closed_on_saturday', models.BooleanField(default=False)),
                ('closed_on_sunday', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurant',
            },
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
