# Generated by Django 5.2.1 on 2025-07-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_restaurantinfo_delete_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantinfo',
            options={'verbose_name': 'Configuration Restaurant', 'verbose_name_plural': 'Configuration Restaurant'},
        ),
    ]
