# Generated by Django 5.2.1 on 2025-07-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_status_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('new', '🔴 Nouveau'), ('confirmed', '🟢 Confirmé'), ('completed', '⚫ Terminé'), ('modified', '🟡 Modifié'), ('cancelled', '⚫ Annulé')], default='new', help_text='Status automatically syncs with reservation status', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='reservation', max_length=50),
        ),
    ]
