# Generated by Django 5.2.1 on 2025-07-29 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_remove_notification_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message Admin', 'verbose_name_plural': 'Messages Admin'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='message_type',
            field=models.CharField(choices=[('new_reservation', '📨 Nouvelle Réservation'), ('email_failed', '❌ Email Échoué'), ('email_success', '✅ Email Envoyé'), ('reservation_confirmed', '✅ Confirmée'), ('reservation_cancelled', '❌ Annulée'), ('info', 'ℹ️ Information')], default='info', max_length=30, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('urgent', '🔴 Urgent'), ('normal', '🟡 Normal'), ('info', '🟢 Info')], default='normal', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lu le'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='reservation_created_1a6f10_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='reservation_is_read_450d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'is_read'], name='reservation_priorit_a7baa1_idx'),
        ),
    ]
