# Generated by Django 5.2.1 on 2025-08-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveIndex(
            model_name='specialdate',
            name='reservation_date_616148_idx',
        ),
        migrations.RemoveField(
            model_name='specialdate',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='specialdate',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Ouvert'),
        ),
        migrations.AddIndex(
            model_name='specialdate',
            index=models.Index(fields=['date', 'is_open'], name='reservation_date_b465e1_idx'),
        ),
    ]
