# Generated by Django 5.2.1 on 2025-08-13 10:52

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP du client'),
        ),
        migrations.AddField(
            model_name='notification',
            name='client_user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='Navigateur client'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email ouvert le'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_opened_by_client',
            field=models.BooleanField(default=False, verbose_name='Email ouvert par client'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email envoyé'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email envoyé le'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token de suivi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu par admin'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lu par admin le'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tracking_token'], name='reservation_trackin_640d66_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['email_opened_by_client'], name='reservation_email_o_483b10_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'email_opened_by_client'], name='reservation_is_read_625a0a_idx'),
        ),
    ]
